require("APAlyzer") || stop("unable to load Package:APAlyzer")
require("GenomicRanges") || stop("unable to load Package:GenomicRanges")
require("GenomicFeatures") || stop("unable to load Package:GenomicFeatures")
require("GenomicAlignments") || stop("unable to load Package:GenomicAlignments")
require("DESeq") || stop("unable to load Package:DESeq")
require("SummarizedExperiment") || stop("unable to load Package:SummarizedExperiment")
require("Rsubread") || stop("unable to load Package:Rsubread")
require("stats") || stop("unable to load Package:stats")
require("testthat") || stop("unable to load testthat")
test_check("APAlyzer")
